### ISSUE TITLE
Ne deluje

### ISSUE THREAD

**Issue by rozmanU14** [rozmanU14/APPR-2015-16#1]
_Zaenkrat_ še ni **nič** napisano

``` R
x<- 1+1
y<- x*42
```

**Comment by jaanos** [comment]
Svetujem ti, da tale issue zapreš, in nasploh sproti zapiraš issueje, ki jih razrešiš. Tako bo lažje slediti problemom, ki se bodo sproti pojavljali.

**Comment by rozmanU14** [comment]
Hvala, bom zaprla. Imam pa se eno vprasanje. Datoteke s podatki v formatu
csv,ki jo imam na githubu, mi v R ne prikaze, kljub temu da sem veckrat
pritisnila gumb za osvezitev. (Datoteko v html formatu pa mi prikaze)
Lep pozdrav, Urska Rozman
Dne 28. nov. 2015 17:24 je oseba "Janoš Vidali" notifications@github.com
napisala:

**Comment by jaanos** [comment]
Imaš pri sebi zadnjo verzijo? Preden začneš z delom, vedno naredi pull, da pridobiš aktualno verzijo iz GitHuba. Seveda tudi po koncu dela naredi commit (lahko seveda tudi večkrat tekom dela) in push, da pošlješ spremembe na GitHub.
