### ISSUE TITLE
ne prikaže datoteke

### ISSUE THREAD

**Issue by rozmanU14** [rozmanU14/APPR-2015-16#2]
datoteke evropa.html mi v R ne prikaže, čeprau sem kliknila PULL in še znak za osvežitev

**Comment by jaanos** [comment]
Datoteko `evropa.html` imaš v mapi `podatki`. Ali ti je tudi tam ne prikaže?

**Comment by rozmanU14** [comment]
Na githubu mi jo pokaze, v R studiu pa ne.

**Comment by jaanos** [comment]
Hmm, to pa je čudno. Poskusi še enkrat narediti pull, pa bodi pozorna na to, ali ti pri tem javi kakšno napako.

**Comment by rozmanU14** [comment]
error: Your local changes to the following files would be overwritten by
merge:
uvoz/uvoz.r
Please, commit your changes or stash them before you can merge.
Updating f659968..44dd0c6
error: The following untracked working tree files would be overwritten by
merge:
podatki/prirastek.csv
Please move or remove them before you can merge.
Aborting

tole napako mi javi

Dne 02. december 2015 19:23 je Janoš Vidali notifications@github.com
napisal/-a:

**Comment by jaanos** [comment]
Aha, očitno si pri sebi delala spremembe na datotekah `uvoz/uvoz.r` in `podatki/prirastek.csv`, ki jih nisi commitala.

V oknu, kjer delaš commit, si lahko pogledaš, za kakšne spremembe gre. Če teh sprememb več ne potrebuješ (npr. ker si isto že naredila na faksu), lahko izbereš datoteko in zgoraj klikneš na _Revert_. Tako se bodo narejene spremembe zavrgle. Če zavržeš vse lokalne spremembe, bo potem možno narediti pull.

V nasprotnem primeru, ko bi rada spremembe obdržala, pa enostavno naredi commit, pri čemer vključiš (vsaj) ti dve datoteki (ali pa eno, če si samo pri eni zavrgla spremembe). Potem lahko narediš pull, vendar lahko v tem primeru prde do konflikta. Če se to zgodi, potem bo potrebno vse konflikte razrešiti. Konflikte izgledajo takole:

```
<<<<<<< HEAD
vsebina iz tvoje kopije
=======
vsebina z repozitorija
>>>>>>> origin/HEAD (ali pa šifra commita)
```

Konflikte razrešiš enostavno tako, da jih prepišeš z ustrezno vsebino (lahko pustiš vsebino iz tvoje kopije, lahko iz repozitorija, ali pa ju kombiniraš oziroma narediš nekaj novega). Ko razrešiš konflikte, narediš nov commit (pri čemer nujno vključiš vse datoteke, kjer so se pojavljali konflikti), šele potem pa bo GitHub sprejel push.

**Comment by jaanos** [comment]
Še to: pri datoteki `uvoz.r` gre za to, da lokalnih sprememb nisi commitala, tako da velja zgoraj opisano. Pri datoteki `prirastek.csv` gre očitno za to, da jo imaš pri sebi, a je še nisi pri sebi vključila v commit. Če je ta datoteka enaka tisti na GitHubu, jo lahko mirno izbrišeš pri sebi, saj se bo znova pojavila, ko narediš pull.

**Comment by rozmanU14** [comment]
Najlepša hvala! Sem odpravila napaki.

Dne 02. december 2015 21:22 je Janoš Vidali notifications@github.com
napisal/-a:
