### ISSUE TITLE
seštevanje stolpcev as.vector

### ISSUE THREAD

**Issue by rozmanU14** [rozmanU14/APPR-2015-16#3]
če stolpec spremenim v as.integer oziroma v as.numeric mi podatke spremeni v neresnične. Ko jih spremenim v as.vector so podatki resnični, vendar mi ne uspe sešteti dveh stolpcev in vrednosti zapisati v nov stolpec.

**Comment by jaanos** [comment]
Sklepam, da gre tukaj za razpredelnico `tabela`, ki si jo uvozila iz CSV. Manjkajoči podatki so tukaj predstavljeni z `-` - ker R tega ne ve, naredi stolpce faktorjev, ti se pa potem napačno pretvorijo z `as.numeric` (prej bi bilo potrebno še pretvoriti v nize z `as.character`).

Bo pa najlažje, če kar pri uvozu poveš, da `-` predstavlja manjkajoče podatke. To narediš tako, da funkciji `read.csv2` dodaš parameter `na.strings = "-"`. Ker so potem nemanjkajoči podatki samo številke, bodo sedaj te res razumljene kot številke in boš lahko z njimi tudi računala.

Mimogrede, opažam, da šumniki v CSV datoteki ne delujejo čisto pravilno - `š`-ji in `ž`-ji so pravilni, `č`-ji pa ne. Očitno si datoteko `prirastek.csv` že shranila v UTF-8, tako da bo najlažje, če jo odpreš v RStudiu ter popraviš znake `è` in `È` v `č` in `Č`.

**Comment by rozmanU14** [comment]
Najlepša hvala

Dne 09. december 2015 19:04 je Janoš Vidali notifications@github.com
napisal/-a:
