### ISSUE TITLE
zemljevidi

### ISSUE THREAD

**Issue by rozmanU14** [rozmanU14/APPR-2015-16#4]
Če narišem zemljevid z eno izmed že obstoječih spremenljivk, zemljevid deluje, če pa ga želim narisati s spremenljivko katerega stolpec sem dodala, pa napiše "Error in eval(expr, envir, enclos) : object 'PRIRAST' not found", čeprav v tabeli ta stolpec je.

**Comment by jaanos** [comment]
Če odkomentiram zadnjo vrstico v `uvoz.r` in narišem zemljevid, mi deluje:

``` R
obc <- pretvori.zemljevid(obc)
ggplot() + geom_polygon(data = obc, aes(x = long, y = lat, group = group, fill = NARAVNI_PRIRAST))
```

Iz napake sklepam, da si poskusila uporabiti za ime stolpca `PRIRAST` namesto `NARAVNI_PRIRAST`.

**Comment by rozmanU14** [comment]
Zdaj mi nariše zemljevid, a če želim pogledati tabelo "View(obc)" mi v stolpcu kjer naj bi bili kraji, napiše samo "DOMŽALE" (OB_UIME)

**Comment by jaanos** [comment]
To je v redu - zdaj imaš v `obc` eno vrstico za vsako točko. RStudio ti prikaže samo prvih 1000 vrstic, od katerih vse pripadajo občini Domžale.
