### ISSUE TITLE
Poročilo in zemljevidi

### ISSUE THREAD

**Issue by jaanos** [rozmanU14/APPR-2015-16#5]
Poročila ti ne prevede, ker se v njem sklicuješ na spremenljivke iz vzorca. Najbolje bo, če del iz vzorca pobrišeš. Seveda bo potrebno dodati še kak graf iz tvojih podatkov.

V datoteki `uvoz/uvoz.r` izpisuješ stanje s `cat`, to pa se potem vidi tudi v poročilu. Da se temu izogneš, namesto `print` raje uporabi ukaz `message`. Ta obvestila se potem ne bodo izpisovala v poročilo.

Zemljevidov ne izrisuj v `uvoz.r`. Lahko si jih shraniš v spremenljivke, ki jih potem izrišeš v poročilu.

**Comment by rozmanU14** [comment]
Izbrisala sem del iz vzorca , vednar mi poročila še vedno ne prevede.Grafa
pa mi ne uspe dodati.

Dne 22. december 2015 01:05 je Janoš Vidali notifications@github.com
napisal/-a:

**Comment by jaanos** [comment]
V zadnjem commitu še vedno vidim celoten del iz vzorca, uvoz pa ne deluje, saj se sklicuješ na neobstoječo spremenljivko `tabela2010`. Imaš morda novejšo verzijo, ki je še nisi pushala?

**Comment by rozmanU14** [comment]
ja, ravno sedaj sem novejšo verzijo pushala. ševedno javlja napako

Dne 22. december 2015 18:39 je Urška Rožman rozman.urska@gmail.com
napisal/-a:

**Comment by jaanos** [comment]
Sedaj je problem ta, da imaš dva bloka z oznako `razpredelnice`. Ni nujno, da ima vsak blok svojo oznako - te pridejo prav predvsem pri grafih, da se lahko nanje sklicuješ. Obstoječe oznake pa morajo biti različne. Tako ustrezna bloka začni z npr. `{r razpredelnica1}` in `{r razpredelnica2}`.

V PDF mi sice še vedno ne prevede, pa nisem povsem prepričan, zakaj. Poskusi prevesti v HTML, to bi moralo delovati.

Da bo pravilno prikazalo tabele, za vsakim blokom kode pusti še prazno vrstico.

Grafov ne riši v `uvoz.r`, ampak jih premakni v poročilo (lahko pa jih v uvozu prripraviš in jih v poročilu samo izpišeš).

Mimogrede, če hočeš imeti seznam, pred in za njim pusti prazno vrstico. Da ti bo hiperpovezave pravilno prikazovalo, jih obdaj z `<>`, npr.

``` markdown
<http://ec.europa.eu/eurostat/web/population-demography-migration-projections/births-fertitily-data/database>
```

**Comment by rozmanU14** [comment]
Hvala! sem popravila. PDF tudi meni ne deluje, HTML pa.

Dne 22. december 2015 19:57 je Janoš Vidali notifications@github.com
napisal/-a:

**Comment by jaanos** [comment]
Bom dodal povezavo. Pri prvih dveh grafih so sicer oznake na osi x nečitljive. Grafu lahko prišteješ npr. `theme(axis.text.x = element_text(angle = 90, vjust = 0.5))`, da se te oznake izpišejo navpično.

Če boš še kaj spreminjala do predstavitve, mi prosim javi, da posodobim povezavo.
