### ISSUE TITLE
prikaz podatkov

### ISSUE THREAD

**Issue by rozmanU14** [rozmanU14/APPR-2015-16#6]
Imam težavo, ,ako bi prikazala podatke za povprečno rodnost po letih glede na spol v grafu, ki sem jih izračunala, ali je dovolj le z besedami napisati ugotovitev?

**Comment by jaanos** [comment]
Kaj točno želiš prikazati - za katero tabelo gre? Če imaš povprečja za vsako državo/občino za več let, potem lahko narediš običajen stolpčni graf, če pa imaš povprečja za vsako leto, lahko narediš črtni ali točkast graf. Če pa imaš en graf (npr. skozi leta) in bi želela prikazati povprečje podatkov na tem grafu, lahko narišeš vodoravno črto tako, da grafu prišteješ npr. `geom_hline(yintercept = povprecje)`, kjer je `povprecje` tvoje izračunano povprečje.

Ugotovitve seveda tudi napiši v poročilu.

**Comment by rozmanU14** [comment]
Najlepsa hvala !
Dne 27. dec. 2015 15:54 je oseba "Janoš Vidali" <notifications@github.com>
napisala:

**Comment by rozmanU14** [comment]
če želim dodati na graf eno vodoravno črto, mi deluje . Kako pa bi na graf
dodala dve črti? (geom_hline(yintercept = povprecje1) + geom_hline(yintercept
= povprecje2) <- tako ne deluje.


Dne 27. december 2015 16:03 je Urška Rožman <rozman.urska@gmail.com>
napisal/-a:

**Comment by jaanos** [comment]
Več vodoravnih črt dodaš tako, da pri `yintercept` podaš vektor koordinat, kamor naj se narišejo črte. Tako lahko grafu prišteješ npr. `geom_hline(yintercept = c(povprecje1, povprecje2), color = c("red", "blue"))`, pa bo črto za `povprecje1` narisalo z rdečo, črto za `povprecje2` pa z modro.

**Comment by rozmanU14** [comment]
Če naredim to, mi nariše samo črto ki je v vektorju vnešena kot zadnja.

Dne 03. januar 2016 18:00 je Janoš Vidali <notifications@github.com>
napisal/-a:

**Comment by rozmanU14** [comment]
Mi deluje, se opravičujem!

Dne 03. januar 2016 18:09 je Urška Rožman <rozman.urska@gmail.com>
napisal/-a:

**Comment by rozmanU14** [comment]
Na graf sem želela narisati 4 vodoravne črte. kar mi je do nedavnega
delovalo, zdaj pa mi nariše le tisto, ki je podana kot zadnja. Zdaj sem
poskusila na tak način:

povprecje2010<-ggplot(tabela) + aes(x = kraj, y = skupni.prirast) +
  geom_point() +theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
+
  geom_point() +
  geom_hline(yintercept = c(povp.pr.2010), color = c( "blue"))
povprecje2011<- povprecje2010 +geom_hline(yintercept = c(povp.pr.2011),
color = c( "orange"))
povprecje2012<- povprecje2011 +geom_hline(yintercept = c(povp.pr.2012),
color = c( "red"))

vendar prav tako nariše le zadnjo.

Dne 03. januar 2016 18:13 je Urška Rožman <rozman.urska@gmail.com>
napisal/-a:

**Comment by jaanos** [comment]
Vodoravne črte ti nariše, če jih navedeš k istemu `geom_hline`, a so na tem grafu tako blizu skupaj, da jih ni mogoče razločiti.

Sicer pa malo premisli, kaj hočeš pokazati s tem grafom. Trenutno rišeš podatke za vse občine in vsa leta na isti točkovni graf, kar ni pregledno, saj npr. ne moreš vedeti, katera točka sploh ustreza kateremu letu. Poleg tega imaš priraste v absolutnih številkah - ker se število prebivalcev med občinami zelo razlikuje, ti potem povprečje ne pove prav veliko. Smiselno bi torej bilo pridobiti še podatke o prebivalstvu v občinah skozi leta, da potem poračunaš priraste kot deleže. Tako lahko izračunaš tudi prirast za celo Slovenijo v vsakem letu, in te podatke prikažeš na grafu.

Točkovni graf ni najbolj primeren način prikaza, ko imaš na kaki osi kategorične podatke. En način bi bil, da uporabiš stolpčni graf - lahko prikažeš npr. podatke za eno leto za večje število občin, ali pa podatke skozi leta (stolpci en ob drugem) za manjše število občin, npr.
```R
ggplot(tabela %>% filter(kraj %in% c("Koper/Capodistria", "Ljubljana", "Maribor")),
       aes(x = kraj, y = skupni.prirast, fill = factor(leto))) +
  geom_bar(stat = "identity", position = "dodge")
```
Druga možnost bi bila, da prikažeš gibanje prirasta skozi leta za nekaj občin, npr.
```R
ggplot(tabela %>% filter(kraj %in% c("Koper/Capodistria", "Ljubljana", "Maribor")),
       aes(x = leto, y = skupni.prirast, group = kraj, color = kraj)) +
  geom_line()
```

Mimogrede, povprečja računaj s funkcijo `mean`. Tako kot pri `sum` lahko podaš parameter `na.rm = TRUE`, ki pa poskrbi še, da se vsota obstoječih vrednosti deli z njihovim številom in ne s številom vseh vrstic (od katerih morda pri nekaterih manjka vrednost).

**Comment by rozmanU14** [comment]
Najlepša hvala!

Dne 08. januar 2016 20:11 je Janoš Vidali <notifications@github.com>
napisal/-a:
