### ISSUE TITLE
Ne prikazuje v html obliki kar v "analiza.r" prikaže

### ISSUE THREAD

**Issue by rozmanU14** [rozmanU14/APPR-2015-16#7]
Ko sem naredila napoved za Slovenijo v "analiza/analiza.r" mi graf prikaže, ko pa ga dodam v poročilo, pa mi ga več ne prevede (niti v html).

**Comment by jaanos** [comment]
Trenutno ti poročila ne prevede, ker se sklicuješ na neobstoječi spremenljivki `ln` in `kvp` (na več mestih v `analiza.r` in v poročilu) - najbrž si tam hotela uporabiti `linearna` oziroma `kvadratna`. Ko sem to popravil, mi je grafe prikazalo tako v HTML, kot tudi v PDF (dvakrat - enkrat, ko jih rišeš v `analiza.r`, drugič pa v poročilu). Pri grafih pri analizi dodaj blokom še parameter `warning = FALSE`, da ti ne bo izpisovalo opozoril o manjkajočih podatkih (lahko pa tudi s `filter` izločiš vrstice, kjer manjkajo podatki, ki jih rišeš).

Sicer pa svetujem, da malo premisliš, kaj prikazuješ na grafih in kaj napoveduješ. Trenutno namreč prikazuješ priraste za vse občine v vsakem letu - ti so zaradi različnih velikosti občin zelo različni, skozi leta pa očitno ni velikih sprememb. Lahko se npr. odločiš, da gledaš priraste za posamezne občine in napoveduješ na podlagi teh, ali pa izračunaš relativne priraste (torej deliš s prebivalstvom občine) in te uporabiš za podatke. Potem razlike ne bodo tako velike, tako da bo mogoče videti tudi manjše spremembe v rasti prebivalstva.

Svetujem tudi, da za vse grafe uporabiš ggplot2. Več različnih modelov lahko prikažeš tako, da grafu prikažeš več funkcij `geom_smooth` (poglej si rešitev zadnje naloge na Tomu).

Še to: opažam, da tudi v `analiza.3.faza.r` narediš veliko zemljevidov, ki jih potem v poročilu narišeš še enkrat. Teh zemljevidov ti ni potrebno dvakrat risati - lahko jih narediš kar v poročilu, ali pa pripraviš v programu in izpišeš v poročilu. Tako svetujem, da odstraniš risanje zemljevidov iz programov - tako se bo tudi poročilo hitreje prevedlo.

**Comment by rozmanU14** [comment]
hvala! Sedaj mi prevede. Absolutne vrednosti pri napovedih pa sem zamenjala
z relativnimi ter izbrisala zemljevide, da se ne ponavljajo.

Dne 15. januar 2016 21:55 je Janoš Vidali <notifications@github.com>
napisal/-a:
