### ISSUE TITLE
Poročilo v PDF

### ISSUE THREAD

**Issue by jaanos** [rozmanU14/APPR-2015-16#8]
Da ti bo poročilo prevedlo v PDF, v oznakah blokov ne sme biti presledkov. Tako zamenjaj `graf 9`, `graf 10`, `graf 11` z `graf9`, `graf10`, `graf11`.

**Comment by rozmanU14** [comment]
sem izbrisala nepotrebne presledke, vednar v pdv še vedno ne prevede.

2016-01-19 2:19 GMT+01:00 Janoš Vidali notifications@github.com:

**Comment by jaanos** [comment]
Meni deluje, tako da ti bom posodobil povezavo.

Kakšno napako pa dobiš?

**Comment by rozmanU14** [comment]
hvala.
napaka pa je tale:
[image: Slika v vrstici 1]

2016-01-19 22:19 GMT+01:00 Janoš Vidali notifications@github.com:

**Comment by jaanos** [comment]
Žal tukaj ne vidim slike. Lahko jo pripneš, če na ta issue odgovoriš na GitHubu - ali pa prepiši sporočilo napake.

**Comment by rozmanU14** [comment]
1. jan. 2016 00.37 je oseba "Janoš Vidali" notifications@github.com
   napisala:
