### ISSUE TITLE
shiny

### ISSUE THREAD

**Issue by rozmanU14** [rozmanU14/APPR-2015-16#9]
Poskušala sem narediti shiny graf. sledila sem že narejenu vzorcu vendar mi dela z grafom (server.r - v analiza.r) sploh ne prikaže. V okencu kjer naj bi se prikazali kraji, pa se pokažejo zgolj zaporedne številke krajev.

**Comment by jaanos** [comment]
Sem ti odprl pull request #10 z delujočim primerom in kratkim opisom.

Svetoval bi ti še, da popraviš podatke v `prirastek.csv`, saj je očitno prišlo do zmede s šumniki. Najbolje bo, če podatke ponovno pridobiš s statističnega urada in urediš datoteko, da bodo podatki pravilni. Pazi seveda, da jo spraviš spet v isto obliko, da ti programa ne bo potrebno spreminjati.

Lahko se tega lotiš tudi tako, da podatke uvoziš v R, jih tam obdelaš kot razpredelnico, nato pa jih nazaj zapišeš v datoteko s pomočjo ukaza `write.csv2`.

**Comment by rozmanU14** [comment]
Najlepša hvala!
Podatke pa bom ponovno uvozila.

Dne 27. januar 2016 20:31 je Janoš Vidali <notifications@github.com>
napisal/-a:

**Comment by rozmanU14** [comment]
Sedaj pa mi niti uvoz več ne deluje, čeprav kode nisem nič spreminjala.
In matrix(x:max, ncol = length(s)) :
  data length [1267] is not a sub-multiple or multiple of the number of
rows [6]


Dne 27. januar 2016 20:37 je Urška Rožman <rozman.urska@gmail.com>
napisal/-a:

**Comment by jaanos** [comment]
Pobriši prazne vrstice na koncu datoteke `prirastek.csv`.

**Comment by rozmanU14** [comment]
Hvala! Mi deluje.

2016-01-27 21:10 GMT+01:00 Janoš Vidali <notifications@github.com>:

**Comment by rozmanU14** [comment]
Kako pa bi shiny vključila v poročilo? zgolj s klicem ui.r in server.r mi
ne prevede.

Dne 27. januar 2016 21:11 je Urška Rožman <rozman.urska@gmail.com>
napisal/-a:
